import type { Metadata } from "next";
import "./globals.css";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/igx2nek.css" />
      </head>
      <body className="antialiased">{children}</body>
    </html>
  );
}
